#  setting up a PostgreSQL database container
services:
  # defines a service named postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=lp1dxing
    # Maps port 5432 of the host machine to port 5432 of the PostgreSQL container. This allows you to connect to the PostgreSQL database using port 5432 on the host machine.
    ports:
      - 5432:5432
    volumes:
      # Mounts a volume named pgdata to the container's /var/lib/postgresql/data directory.
      - pgdata:/var/lib/postgresql/data
#  This section defines Docker volumes that can be used by services
volumes:
  pgdata:
